### ISSUE TITLE
Crypto-bridge breaks Docker image building

### ISSUE THREAD

**Issue by ItsLuized** [Rpc-h/RPCh#188]
`crypto-bridge` errors out when building the container images for `exit-node`, `discovery-platform`, `funding-service` and  `rpc-server`.

## Expected Behavior

The docker images for the above mentioned packages or apps should build successfully.

## Current Behavior

We get the following error:
```bash
@rpch/crypto-bridge:build: cache miss, executing 7efde1ebf3bdf5a5
@rpch/crypto-bridge:build: $ rimraf index.js index.d.ts nodejs web && tsup
@rpch/crypto-bridge:build: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
@rpch/crypto-bridge:build:     at new NodeError (node:internal/errors:387:5)
@rpch/crypto-bridge:build:     at createRequire (node:internal/modules/cjs/loader:1284:11)
@rpch/crypto-bridge:build:     at dynamicImport (/app/node_modules/bundle-require/dist/index.cjs:75:154)
@rpch/crypto-bridge:build:     at extractResult (/app/node_modules/bundle-require/dist/index.cjs:190:21)
@rpch/crypto-bridge:build:     at async run (/app/node_modules/bundle-require/dist/index.cjs:228:17)
@rpch/crypto-bridge:build: error Command failed with exit code 1.
@rpch/crypto-bridge:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@rpch/crypto-bridge:build: ERROR: command finished with error: command (/app/packages/crypto-bridge) yarn run build exited (1)
```

## Steps to Reproduce

1. Go the the directory of any of the packages or apps mentioned above (Eg: apps/exit-node/)
2. run `docker build -f Dockerfile ../../`

_Were you able to reproduce the bug using the above steps consistently each time?_ **YES**

**Comment by diegoalzate** [comment]
Fixed in #181
