### ISSUE TITLE
LevelDB start failure in Docker container

### ISSUE THREAD

**Issue by robertkiel** [Rpc-h/RPCh#219]
## Expected Behavior

Follow instructions on `access.rcph.net`
```
docker run -e DEBUG="rpch*,-*verbose,-*metrics" -e RESPONSE_TIMEOUT=10000 -e DISCOVERY_PLATFORM_API_ENDPOINT=https://staging.discovery.rpch.tech -e PORT=8080 -e DATA_DIR=app -e CLIENT=***  --name rpc-server -p 8080:8080 --rm  sitilge/rpc-server:36182ae
```

which should kick off RPCh server start

## Current Behavior

Docker startup falis with

```
root@debian-robert:/home/robert/Documents# docker run -e DEBUG="rpch*,-*verbose,-*metrics" -e RESPONSE_TIMEOUT=10000 -e DISCOVERY_PLATFORM_API_ENDPOINT=https://staging.discovery.rpch.tech -e PORT=8080 -e DATA_DIR=app -e CLIENT=*** --name rpc-server -p 8080:8080 --rm sitilge/rpc-server:36182ae
2023-02-16T12:16:20.831Z rpch:rpc-server Starting rpc-server

/app/node_modules/levelup/lib/levelup.js:127
      return callback(new OpenError(err))
                      ^
Error [OpenError]: IO error: app/LOCK: No such file or directory
    at /app/node_modules/levelup/lib/levelup.js:127:23
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at onopen (/app/node_modules/deferred-leveldown/deferred-leveldown.js:49:14)
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
Emitted 'error' event on LevelUP instance at:
    at /app/node_modules/levelup/lib/levelup.js:56:19
    at /app/node_modules/levelup/lib/levelup.js:127:14
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at onopen (/app/node_modules/deferred-leveldown/deferred-leveldown.js:49:14)
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:41:14 {
  [cause]: [Error: IO error: app/LOCK: No such file or directory]
}
```

**Comment by robertkiel** [comment]
Happens if Docker runs out of space
