### ISSUE TITLE
Connection refused by server Error

### ISSUE THREAD

**Issue by Jaguaras** [Rpc-h/RPCh#252]
## Expected Behavior

When launching RPCh server, trying to open metamask with RPCh network or swapping, listening node should not crash.

## Current Behavior

It crashed after a launch of RPCh server, or when trying to open MM with already added RPCh network or just trying to swap.

What I noticed it fails with the same server IP: 34.65.146.242

## Steps to Reproduce

1. Try to launch RPC server 

_Were you able to reproduce the bug using the above steps consistently each time?_ **YES**

## Detailed Description

OS: Mac OS / Ventura 13.0.1 (22A400)
Browser: Chrome 110.0.5481.100 (Official Build) (arm64)

## Logs

```
andrius@Andriuss-MBP-4 ~ % docker run -e DEBUG="rpch*,-*metrics" -e RESPONSE_TIMEOUT=10000 -e DISCOVERY_PLATFORM_API_ENDPOINT=https://staging.discovery.rpch.tech -e PORT=8080 -e DATA_DIR=app -e CLIENT=mean-listen-attack-follow-join  --name rpc-server -p 8080:8080 --rm  europe-west6-docker.pkg.dev/rpch-375921/rpch/rpc-server:f8a6bf7
Unable to find image 'europe-west6-docker.pkg.dev/rpch-375921/rpch/rpc-server:f8a6bf7' locally
f8a6bf7: Pulling from rpch-375921/rpch/rpc-server
bb263680fed1: Pull complete 
90145816ab6f: Pull complete 
0481404eede0: Pull complete 
2d550157791a: Pull complete 
94647e4b26ba: Pull complete 
fb892122cab7: Pull complete 
9c17dc916952: Pull complete 
404539a1c054: Pull complete 
a8a4775c6e0c: Pull complete 
bde8d25c9fd8: Pull complete 
86d58ccdd5ec: Pull complete 
930f82252984: Pull complete 
Digest: sha256:b9b66c54ce538b242e3f49412c0d463e5d3835c946eba9fae2ff847f6af8278f
Status: Downloaded newer image for europe-west6-docker.pkg.dev/rpch-375921/rpch/rpc-server:f8a6bf7
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-02-27T15:00:23.670Z rpch:rpc-server Starting rpc-server
2023-02-27T15:00:23.682Z rpch:rpc-server:verbose Initializing DB at app
2023-02-27T15:00:23.703Z rpch:rpc-server:verbose Initializing RPCh SDK {
  timeout: 10000,
  discoveryPlatformApiEndpoint: 'https://staging.discovery.rpch.tech'
}
2023-02-27T15:00:23.723Z rpch:sdk:verbose Using 'node' RPCh crypto implementation
2023-02-27T15:00:23.894Z rpch:sdk:verbose Selecting entry node
2023-02-27T15:00:24.779Z rpch:sdk:verbose Selected entry node {
  apiEndpoint: 'http://34.65.146.242/',
  apiToken: 'PleaseChangeMe',
  peerId: '16Uiu2HAm9o1FuLmgYPWYhw1qe2sQB3TwYCfkxWtJWAPMvurUPBcm'
}
2023-02-27T15:00:24.804Z rpch:sdk:verbose Fetching exit nodes
2023-02-27T15:00:25.400Z rpch:sdk:verbose Fetched exit nodes 4
2023-02-27T15:00:25.408Z rpch:rpc-server Starting rpc-server
2023-02-27T15:00:25.434Z rpch:rpc-server:server HORP rpc-server is listening on 0.0.0.0:8080
2023-02-27T15:00:26.383Z rpch:rpc-server:server:verbose request received {"id":545959650038978,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]} https://primary.gnosis-chain.rpc.hoprtech.net
2023-02-27T15:00:26.431Z rpch:rpc-server:verbose Sending request 453443 16Uiu2HAm9o1FuLmgYPWYhw1qe2sQB3TwYCfkxWtJWAPMvurUPBcm|0x11034e418e36369b8e771ead8b1fd28b56351226a2970b448344ccefbdd70765d364000001869363a4a448c4e347cede105291c71a09ee6de3b1489c480d0d75664fd50c3b01baedf630d16d831138e549501129bfa2e79fa8e1c05967e1b2ee910fc48b0a986a8ce3a2c26a0520e472f56490e56c923f7dbacc327ce8262eafce8d9eed0d75d11b1bf5a11fa58cb088dc457d26d54ef6d5b4d137d733fb455f1b533a762ad07f4ccd38dc2fbd28d703ce44058311f59aacf4be23ee9b
2023-02-27T15:00:26.444Z rpch:common:hoprd:verbose sending message to HOPRd node 453443|0|2|16Uiu2HAm9o1FuLmgYPWYhw1qe2sQB3TwYCfkxWtJWAPMvurUPBcm|0x11034e418e36369b8e771ead8b1fd28b56351226a2970b448344ccefbdd70765d364000001869363a4a448c4e347cede105291c71a09ee6de3b1489c480d0d75664fd50c3b01baedf630d16d831138e549501129bfa2e79fa8e1c05967e1b2ee910fc48b0a986a8ce3a2c26a0520e472f56490e56c923f7dbacc327ce8262eafce8d9eed0d75d11b1bf5a11fa58cb088dc457d26d54ef6d5b4d137d733fb455f1b533a762 16Uiu2HAmKBQvdifJHqKigKnAFTqyYPMD472r4kx7ZXxMhPuzYh4v with path direct
2023-02-27T15:00:26.462Z rpch:common:hoprd:verbose sending message to HOPRd node 453443|1|2|ad07f4ccd38dc2fbd28d703ce44058311f59aacf4be23ee9b 16Uiu2HAmKBQvdifJHqKigKnAFTqyYPMD472r4kx7ZXxMhPuzYh4v with path direct
2023-02-27T15:00:26.482Z rpch:common:cache:verbose total number of segments 0
2023-02-27T15:00:26.484Z rpch:sdk:request-cache:verbose requests 1
2023-02-27T15:00:27.485Z rpch:common:cache:verbose total number of segments 0
2023-02-27T15:00:27.490Z rpch:sdk:request-cache:verbose requests 1
2023-02-27T15:00:28.489Z rpch:common:cache:verbose total number of segments 0
2023-02-27T15:00:28.493Z rpch:sdk:request-cache:verbose requests 1
2023-02-27T15:00:29.493Z rpch:common:cache:verbose total number of segments 0
2023-02-27T15:00:29.496Z rpch:sdk:request-cache:verbose requests 1
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 34.65.146.242:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/app/node_modules/ws/lib/websocket.js:1004:13)
    at ClientRequest.<anonymous> (/app/node_modules/ws/lib/websocket.js:856:5)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '34.65.146.242',
  port: 80
}
```

**Comment by nionis** [comment]
Lets reopen this issue if it exists in our production environment
