### ISSUE TITLE
Websocket error sending request

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/RPCh#261]
After selecting a new entry node, a websocket connection is established. If that ws connection throws an error, there is nothing handling that error, it just bubbles up.

## Possible solution
- on every ws error, re establish connection

## Logs

```
  apiEndpoint: 'http://34.65.114.150:3001/',
  apiToken: '^binary6wire6GLEEMAN9urbanebetween1watch^',
  peerId: '16Uiu2HAm8F1u2PvQLq2mmHTBnXPud9KkxH7oa1bxemaL93EFn34m'
}
2023-03-02T15:30:51.694Z rpch:sdk:verbose got new entry node
2023-03-02T15:30:51.695Z rpch:rpc-server:verbose Sending request 518406 16Uiu2HAm8F1u2PvQLq2mmHTBnXPud9KkxH7oa1bxemaL93EFn34m|0x1103e402dab9ff1c25fb41c94884d88705fc2a3bb9b7bfc9d7d3e795b50ca7607b6d00000186a2f292afe9301603e2ca38a12231f26a2d70e49bab68fa027270342e33bf81635ae8fe4e76b40b87fe9ec4091bcf6e425f462fdf241e47dfdafa0045d639ff03148844a07639dc8b25bdff26d6701b317625ea6455f508d36689b8fde6eaaa43df3ceb794a320947c68bb1a75eceb85d5983daab6c1a37092fa9b81dd6cf29f7eb4113814c56ff5847fd5e5d060803b2
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: WebSocket was closed before the connection was established
    at WebSocket.close (/app/node_modules/ws/lib/websocket.js:285:7)
    at SDK.<anonymous> (/app/packages/common/build/hoprd.js:137:8)
    at SDK.<anonymous> (/app/packages/sdk/build/index.js:113:16)
    at Generator.next (<anonymous>)
    at fulfilled (/app/packages/sdk/build/index.js:29:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/app/node_modules/ws/lib/websocket.js:1004:13)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)


```

**Comment by esterlus** [comment]
yes
