### ISSUE TITLE
rpc-server:  Unhandled 'error' event at WebSocket was closed before the connection was established

### ISSUE THREAD

**Issue by mjadach-iv** [Rpc-h/RPCh#335]
## Expected Behavior

 --

## Current Behavior

 --

## (Optional) Possible Solution

 --

## Steps to Reproduce

 --

_Were you able to reproduce the bug using the above steps consistently each time?_ **YES**/**NO**

## Context (Environment)

 --

## Detailed Description

 --

## Logs

```
 rpch:sdk:reliability-score node 16Uiu2HAmSxUgy3UXdESqvTdKxsdFidHfQ3nd8JoLxjk98TvegB4Y is a fresh node with 0.2 reliability score +1ms
  rpch:sdk:reliability-score node 16Uiu2HAmSxUgy3UXdESqvTdKxsdFidHfQ3nd8JoLxjk98TvegB4Y is a fresh node with 0.2 reliability score +1ms
  rpch:sdk:reliability-score node 16Uiu2HAmSxUgy3UXdESqvTdKxsdFidHfQ3nd8JoLxjk98TvegB4Y is a fresh node with 0.2 reliability score +2ms
  rpch:sdk request 325244 expired +1s
  rpch:sdk request 190881 expired +1ms
  rpch:sdk request 653000 expired +0ms
  rpch:sdk request 852784 expired +0ms
  rpch:sdk request 358430 expired +0ms
  rpch:sdk request 999044 expired +0ms
  rpch:sdk request 599225 expired +0ms
liability score +1ms
  rpch:sdk:reliability-score node 16Uiu2HAmSxUgy3UXdESqvTdKxsdFidHfQ3nd8JoLxjk98TvegB4Y has a 0.3333333333333333 reliability score +0ms
  rpch:sdk:reliability-score node 16Uiu2HAmSxUgy3UXdESqvTdKxsdFidHfQ3nd8JoLxjk98TvegB4Y has a 0.3333333333333333 reliability score +0ms
  rpch:common:hoprd Closing HOPRd listener +8m
  rpch:common:hoprd Closing HOPRd listener +11ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: WebSocket was closed before the connection was established
    at WebSocket.close (C:\dev\rpch\RPCh\node_modules\ws\lib\websocket.js:285:14)
    at SDK.<anonymous> (C:\dev\rpch\RPCh\packages\common\build\hoprd.js:135:8)
    at SDK.<anonymous> (C:\dev\rpch\RPCh\packages\sdk\build\index.js:110:14)
    at Generator.next (<anonymous>)
    at fulfilled (C:\dev\rpch\RPCh\packages\sdk\build\index.js:29:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (C:\dev\rpch\RPCh\node_modules\ws\lib\websocket.js:1002:13)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## (Optional) Possible Implementation

--

**Comment by mjadach-iv** [comment]
[logs-rpc-server.log](https://github.com/Rpc-h/RPCh/files/11211916/logs-rpc-server.log) - from session with Diego
